### ISSUE TITLE
How to change the news feed?

### ISSUE THREAD

**Issue by kryptics** [maxbbraun/mirror#4]
I try adding others but they won't show up. I would like to use this - any ideas? thanks in advance...

http://hosted.ap.org/dynamic/fronts/NOTICIAS_DEPORTIVAS?SITE=AP&SECTION=HOME

**Comment by kryptics** [comment]
I found the links 
http://hosted2.ap.org/APDEFAULT/APNewsFeeds
but i keep getting errors, any ideas?

`03-02 20:19:06.448 24562-24613/net.maxbraun.mirror E/News: Parsing news XML response failed: 
                                                           org.xmlpull.v1.XmlPullParserException: unexpected type (position:END_DOCUMENT null@1:1 in java.io.StringReader@b3b585d) 
                                                               at org.kxml2.io.KXmlParser.nextTag(KXmlParser.java:2054)
                                                               at net.maxbraun.mirror.News.getData(News.java:61)
                                                               at net.maxbraun.mirror.News.getData(News.java:18)
                                                               at net.maxbraun.mirror.DataUpdater.update(DataUpdater.java:105)
                                                               at net.maxbraun.mirror.DataUpdater.access$000(DataUpdater.java:16)
                                                               at net.maxbraun.mirror.DataUpdater$1.run(DataUpdater.java:81)
                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                               at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:279)
                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:152)
                                                               at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)
`

**Comment by kryptics** [comment]
Ok never mind the link works now

**Comment by parsons-owen** [comment]
how did you get this to work? i live in the uk so want to use one of these 3 feeds: 
http://feeds.bbci.co.uk/news/rss.xml
http://feeds.skynews.com/feeds/rss/uk.xml
http://feeds.reuters.com/reuters/UKTopNews

BBC or Sky is probably better option but i imagine it has something to do with it being RSS and not Atom feed? this is my first time working on an android app so its probably something obvious?
